let jsonData=[
    {
        "Name":"Harry",
        "Age":21,
        "Class":"Gryffindor"
    },
    {
        "Name":"Ron",
        "Age":22,
        "Class":"Gryffindor"   
    },
    {
        "Name":"Hermon",
        "Age":21,
        "Class":"Gryffindor"
    }
]
/*
{
       "Name":"Harry",
        "Age":21,   
        "Class":"Gryffindor"
}
*/
console.log(jsonData[0].Name);
console.log(jsonData[0].Age);
console.log(jsonData[0].Class);